apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
   containers:
     - name: simple-webapp-color
       image: simple-webapp-color
       ports:
          - containerPort: 8080
       env:
         - name: DB_HOST
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: DB_Host
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: DB_Password


