apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 808
      securityContext:
        runAsUser: 1010
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
  # securityContext can be defined at the pod level and at the container level
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
