apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
      app: myapp

spec:
  template:
    metadata:
      name: myapp-yaml-files
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector: # major difference between rc and rs
    matchLabels:
      type: front-end